### ISSUE TITLE
Report generation for agent matrix report workbook fails due to invalid characters

### ISSUE THREAD

**Issue by alexafshar** [Appdynamics/config-assessment-tool#105]
The stack trace:

2022-11-09 20:21:30,706 [ERROR] Traceback (most recent call last):
  File "/backend/core/Engine.py", line 197, in run
    await self.process()
  File "/backend/core/Engine.py", line 339, in process
    report.createWorkbook(self.maturityAssessmentSteps, self.controllerData, self.jobFileName)
  File "/backend/output/reports/AgentMatrixReport.py", line 205, in createWorkbook
    writeUncoloredRow(
  File "/backend/util/excel_utils.py", line 42, in writeUncoloredRow
    sheet[f"{colIdx}{rowIdx}"] = cell
  File "/backend/.venv/lib/python3.9/site-packages/openpyxl/worksheet/worksheet.py", line 313, in __setitem__
    self[key].value = value
  File "/backend/.venv/lib/python3.9/site-packages/openpyxl/cell/cell.py", line 215, in value
    self._bind_value(value)
  File "/backend/.venv/lib/python3.9/site-packages/openpyxl/cell/cell.py", line 194, in _bind_value
    value = self.check_string(value)
  File "/backend/.venv/lib/python3.9/site-packages/openpyxl/cell/cell.py", line 162, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError

There are edge case where corrupt characters end up in agent metadata that is pulled from the controller API which trips up the excel report generation.

**Comment by alexafshar** [comment]
fixed in v1.5.9.4
