### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by eugenebreenire** [Appdynamics/config-assessment-tool#118]
2023-04-28 13:19:52,175 [INFO] Running Software Version: v1.5.9.5
2023-04-28 13:19:52,524 [INFO] SaaS controller detected. It is recommended to use a maximum of 50 concurrent connections.
2023-04-28 13:19:52,538 [INFO] Setting concurrent connections to 50.
2023-04-28 13:19:52,552 [INFO] Using password from jobfile
2023-04-28 13:19:52,560 [INFO] ----------Input Validation----------
2023-04-28 13:19:52,564 [INFO] Validating Thresholds - DefaultThresholds
2023-04-28 13:19:52,566 [INFO] Validating Controller Login(s) for Job - 
2023-04-28 13:19:54,330 [INFO] ----------Extract----------
2023-04-28 13:19:54,338 [INFO] .saas.appdynamics.com - Extracting APM Applications
2023-04-28 13:19:54,449 [INFO] .saas.appdynamics.com - EUM Applications
2023-04-28 13:19:54,602 [INFO] .saas.appdynamics.com - MRUM Applications
2023-04-28 13:19:54,799 [INFO] .saas.appdynamics.com - Extracting Servers
2023-04-28 13:21:21,602 [INFO] .saas.appdynamics.com - Extracting Controller Configurations
2023-04-28 13:21:21,886 [INFO] .saas.appdynamics.com - Extracting Dashboards
2023-04-28 13:21:26,134 [INFO] .saas.appdynamics.com - Extracting Licenses
2023-04-28 13:21:26,565 [INFO] .saas.appdynamics.com - Extracting Agent Details
2023-04-28 13:21:27,680 [INFO] .saas.appdynamics.com - Extracting CustomMetrics
2023-04-28 13:21:34,163 [INFO] .saas.appdynamics.com - Extracting Synthetics
2023-04-28 13:21:35,189 [ERROR] Traceback (most recent call last):
  File "/backend/core/Engine.py", line 198, in run
    await self.process()
  File "/backend/core/Engine.py", line 332, in process
    await jobStep.extract(self.controllerData)
  File "/backend/extractionSteps/general/Synthetics.py", line 77, in extract
    job["averageDuration"] = syntheticSessionData[idx].data["AVG_DURATION"][job["config"]["id"]]
TypeError: list indices must be integers or slices, not str

2023-04-28 13:32:44,223 [INFO] Running from source/docker, using / as root directory
2023-04-28 13:32:44,224 [INFO]

**Comment by alexafshar** [comment]
fixed in v1.5.9.6
