### ISSUE TITLE
Report phase crashes near end

### ISSUE THREAD

**Issue by SimonFinch63** [Appdynamics/config-assessment-tool#124]
2023-07-28 13:56:32,075 [DEBUG] STREAM b'IDAT' 1109 11146
2023-07-28 13:56:32,090 [ERROR] Traceback (most recent call last):
  File "pptx/slide.py", line 259, in __getitem__
  File "src/lxml/etree.pyx", line 1178, in lxml.etree._Element.__getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core/Engine.py", line 199, in run
  File "core/Engine.py", line 362, in finalize
  File "output/presentations/cxPptFsoUseCases.py", line 572, in createCxHamUseCasePpt
  File "output/presentations/cxPptFsoUseCases.py", line 609, in generateRemediationSlides
  File "pptx/slide.py", line 261, in __getitem__
IndexError: slide index out of range

I have tried running with DefaultThresholds and with our Custom Thresholds, same result, same error

**Comment by alexafshar** [comment]
Hi, 
Can't see anything that would raise a flag.  Can ensure you are using the latest release as of today (1.5.9.8).  what method of installation did you use.    Its hard from this snippet to ascertain the issue.  If you'd like to email me your full log file (please don't post here), I can further investigate.   aleafsha@cisco.com

**Comment by alexafshar** [comment]
Not able to reproduce and provided some suggestions on it through direct email. The executable linux bundle works as I provided feedback on that @SimonFinch63  but if you try the suggestions I had in email and any worked please update this ticket for everyone's benefit.    If not, I'll keep this ticket open in case anyone else has come across it.

**Comment by SimonFinch63** [comment]
I have tested 1.6 on both Windows and Linux, Windows works well, Linux crashes with the same errors as 1.5.9.8.

2024-02-142024-02-14 16:57:05,046 [DEBUG] no evaluation found, ignoring expression: Find online documents for <a href='https://docs.appdynamic 16:57:05,141 [DEBUG] STREAM b'PLTE' 41 768
2024-02-14 16:57:05,141 [DEBUG] STREAM b'tRNS' 821 255
2024-02-14 16:57:05,141 [DEBUG] STREAM b'pHYs' 1088 9
2024-02-14 16:57:05,141 [DEBUG] STREAM b'IDAT' 1109 11146
2024-02-14 16:57:05,141 [DEBUG] STREAM b'IHDR' 16 13
2024-02-14 16:57:05,141 [DEBUG] STREAM b'PLTE' 41 768
2024-02-14 16:57:05,141 [DEBUG] STREAM b'tRNS' 821 255
2024-02-14 16:57:05,142 [DEBUG] STREAM b'pHYs' 1088 9
2024-02-14 16:57:05,142 [DEBUG] STREAM b'IDAT' 1109 11146
2024-02-14 16:57:05,148 [DEBUG] STREAM b'IHDR' 16 13
2024-02-14 16:57:05,148 [DEBUG] STREAM b'PLTE' 41 768
2024-02-14 16:57:05,148 [DEBUG] STREAM b'tRNS' 821 255
2024-02-14 16:57:05,148 [DEBUG] STREAM b'pHYs' 1088 9
2024-02-14 16:57:05,148 [DEBUG] STREAM b'IDAT' 1109 11146
2024-02-14 16:57:05,149 [DEBUG] STREAM b'IHDR' 16 13
2024-02-14 16:57:05,149 [DEBUG] STREAM b'PLTE' 41 768
2024-02-14 16:57:05,149 [DEBUG] STREAM b'tRNS' 821 255
2024-02-14 16:57:05,149 [DEBUG] STREAM b'pHYs' 1088 9
2024-02-14 16:57:05,149 [DEBUG] STREAM b'IDAT' 1109 11146
2024-02-14 16:57:05,163 [ERROR] Traceback (most recent call last):
  File "pptx/slide.py", line 259, in __getitem__
  File "src/lxml/etree.pyx", line 1178, in lxml.etree._Element.__getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core/Engine.py", line 207, in run
  File "core/Engine.py", line 370, in finalize
  File "output/presentations/cxPptFsoUseCases.py", line 572, in createCxHamUseCasePpt
  File "output/presentations/cxPptFsoUseCases.py", line 609, in generateRemediationSlides
  File "pptx/slide.py", line 261, in __getitem__
IndexError: slide index out of range

2024-02-14 16:57:05,166 [DEBUG] controller.prod.appd-saas.srv.westpac.com.au - Closing connection
2024-02-14 16:57:05,167 [DEBUG] asyncio - Task count: 2 - EventLoop delay 72.2983
