### ISSUE TITLE
error creating DefaultJobPCI-Synthetics.xlsx

### ISSUE THREAD

**Issue by diegohormazabal** [Appdynamics/config-assessment-tool#125]
`2023-09-03 03:30:49,469 [DEBUG] Saving Dashboard Workbook
2023-09-03 03:30:51,420 [INFO] Creating presentation from output folder: DefaultJobPCI
2023-09-03 03:30:51,544 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,549 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,550 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,550 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,550 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,550 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IHDR' 16 13
2023-09-03 03:30:51,551 [DEBUG] STREAM b'IDAT' 41 32768
2023-09-03 03:30:51,594 [INFO] Creating CX HAM Use Case PPT for DefaultJobPCI
2023-09-03 03:30:51,956 [ERROR] Traceback (most recent call last):
  File "core\Engine.py", line 199, in run
  File "core\Engine.py", line 362, in finalize
  File "output\presentations\cxPptFsoUseCases.py", line 527, in createCxHamUseCasePpt
  File "output\presentations\cxPptFsoUseCases.py", line 66, in __init__
  File "pandas\util\_decorators.py", line 311, in wrapper
  File "pandas\io\excel\_base.py", line 457, in read_excel
  File "pandas\io\excel\_base.py", line 1376, in __init__
  File "pandas\io\excel\_base.py", line 1250, in inspect_excel_format
  File "pandas\io\common.py", line 795, in get_handle
FileNotFoundError: [Errno 2] No such file or directory: 'output/DefaultJobPCI\\DefaultJobPCI-Synthetics.xlsx'

2023-09-03 03:30:51,956 [DEBUG] localhost - Closing connection
2023-09-03 03:30:51,956 [DEBUG] asyncio - Task count: 2 - EventLoop delay 3.0310

**Comment by alexafshar** [comment]
Possibly due to no Synthetics job available over the prior 24 hours when you ran the tool ?   the config tool operates mostly on the last 24 hours data set when hitting the API's.    If that is the case, and you'd like me to look at it further, email me directly with the full log file. Do not post here!     aleafsha@cisco.com

**Comment by aridnei** [comment]
I see similar error. Like @alexafshar said I think it can be due no Synthetics found...
--
08:59:27  2023-09-15 04:59:27,100 [INFO] Creating Synthetics Report Workbook
**08:59:27  2023-09-15 04:59:27,101 [WARNING] No data found for Synthetics**
08:59:27  2023-09-15 04:59:27,101 [INFO] Creating Dashboard Report Workbook
09:00:48  2023-09-15 05:00:36,929 [INFO] Creating presentation from output folder: DefaultJob
09:00:48  2023-09-15 05:00:45,707 [INFO] Creating CX HAM Use Case PPT for DefaultJob
09:01:15  2023-09-15 05:01:12,831 [ERROR] Traceback (most recent call last):
09:01:15    File "/config-assessment-tool/backend/core/Engine.py", line 199, in run
09:01:15      self.finalize(startTime)
09:01:15    File "/config-assessment-tool/backend/core/Engine.py", line 362, in finalize
09:01:15      createCxHamUseCasePpt(self.jobFileName)
09:01:15    File "/config-assessment-tool/backend/output/presentations/cxPptFsoUseCases.py", line 527, in createCxHamUseCasePpt
09:01:15      excels = ExcelSheets(directory,
09:01:15    File "/config-assessment-tool/backend/output/presentations/cxPptFsoUseCases.py", line 66, in __init__
09:01:15      self.workbooks[filename] = pd.read_excel(full_path, sheet_name=None)
09:01:15    File "/config-assessment-tool/backend/.venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
09:01:15      return func(*args, **kwargs)
09:01:15    File "/config-assessment-tool/backend/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 457, in read_excel
09:01:15      io = ExcelFile(io, storage_options=storage_options, engine=engine)
09:01:15    File "/config-assessment-tool/backend/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1376, in __init__
09:01:15      ext = inspect_excel_format(
09:01:15    File "/config-assessment-tool/backend/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1250, in inspect_excel_format
09:01:15      with get_handle(
09:01:15    File "/config-assessment-tool/backend/.venv/lib/python3.9/site-packages/pandas/io/common.py", line 795, in get_handle
09:01:15      handle = open(handle, ioargs.mode)
09:01:15  FileNotFoundError: [Errno 2] No such file or directory: 'output/DefaultJob/DefaultJob-Synthetics.xlsx'

**Comment by alexafshar** [comment]
I'll add a handler to catch this particular exception and simply INFO report on missing synthetics job instead.

**Comment by alexafshar** [comment]
fixed in v1.6.1
