### ISSUE TITLE
CAT falls over at the analyze stage when running job file with allot of apps excluded

### ISSUE THREAD

**Issue by Gerard1967** [Appdynamics/config-assessment-tool#135]
024-03-07 21:18:30,480 [INFO] ----------Analyze----------
2024-03-07 21:18:30,481 [INFO] [.saas.appdynamics.com](https://aviva1.saas.appdynamics.com/) - Analyzing AppAgentsAPM
2024-03-07 21:18:30,508 [INFO] [.saas.appdynamics.com](https://aviva1.saas.appdynamics.com/) - Analyzing MachineAgentsAPM
2024-03-07 21:18:30,519 [INFO] [.saas.appdynamics.com](https://aviva1.saas.appdynamics.com/) - Analyzing BusinessTransactionsAPM
2024-03-07 21:18:30,530 [INFO] [.saas.appdynamics.com](https://aviva1.saas.appdynamics.com/) - Analyzing BackendsAPM
2024-03-07 21:18:30,530 [ERROR] Traceback (most recent call last):
  File "/backend/core/Engine.py", line 344, in process
    jobStep.analyze(self.controllerData, self.thresholds)
  File "/backend/extractionSteps/maturityAssessment/apm/BackendsAPM.py", line 120, in analyze
    next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/core/Engine.py", line 205, in run
    await self.process()
RuntimeError: coroutine raised StopIteration

**Comment by alexafshar** [comment]
verified bug

**Comment by alexafshar** [comment]
after debugging, this is not due to exclude filter at all.  configuration attribute "backend.registration.limit" is not returned for certain apps while using an iterator and hence coroutine errors out which is not desirable.  Fixed with error handler to set to default.

**Comment by Gerard1967** [comment]
Thank you Alex - looking forward to testing it out this week 🙂
________________________________

**Comment by bhjelmar** [comment]
gotta love flaky apis lol

**Comment by alexafshar** [comment]
fix released with v1.6.1
