### ISSUE TITLE
Report generation fails while extracting server metrics

### ISSUE THREAD

**Issue by alexafshar** [Appdynamics/config-assessment-tool#136]
Due to garbled characters that can end up as machineId string over time, parsing of API payload can fail.    This is similar to #109 accept the failure happens even further up the chain.  Need to re-examine and broaden the exception handler scope so to catch all case.  

stack trace

<code>
2023-10-26 16:25:38,767 [INFO] xxxxx.xxxx.xxxxx.com - Extracting Servers
2023-10-26 16:25:38,826 [ERROR] Traceback (most recent call last):
  File "/backend/core/Engine.py", line 205, in run
    await self.process()
  File "/backend/core/Engine.py", line 340, in process
    await jobStep.extract(self.controllerData)
  File "/backend/extractionSteps/general/ControllerLevelDetails.py", line 38, in extract
    hostInfo["servers"] = (await controller.getServers()).data
  File "/backend/api/appd/AppDService.py", line 755, in getServers
    machineIds = [serverKey["machineId"] for serverKey in serverKeys.data["machineKeys"]]
TypeError: list indices must be integers or slices, not str

2023-10-26 16:25:59,951 [INFO] Running from source/docker, using / as root directory
2023-10-26 16:25:59,952 [INFO] 
</code>

**Comment by alexafshar** [comment]
fix released with v1.6.1
