### ISSUE TITLE
SaaS Controller added TLS 1.3 support, All versions of CA, Linux & Windows stopped working

### ISSUE THREAD

**Issue by SimonFinch63** [Appdynamics/config-assessment-tool#139]
AppDynamics SaaS Operations Team added support for TLS 1.3 and all versions of CA, both windows & Linux have stopped working.

CA successfully logs in to the controller, but then crashes a few seconds later with these errors in the log:

 2024-04-08 09:48:25,053 [INFO] Running Software Version: v1.6
2024-04-08 09:48:30,157 [WARNING] Unable to get latest tag from https://api.github.com/repos/appdynamics/config-assessment-tool/tags
2024-04-08 09:48:30,159 [INFO] On-Premise controller detected. It is recommended to use a maximum of 10 concurrent connections.
2024-04-08 09:48:30,160 [INFO] Setting concurrent connections to 10.
2024-04-08 09:48:30,166 [INFO] Using password from jobfile
2024-04-08 09:48:30,166 [INFO] ----------Input Validation----------
2024-04-08 09:48:30,167 [INFO] Validating Thresholds - DefaultThresholds
2024-04-08 09:48:30,168 [INFO] Validating Controller Login(s) for Job - SaaS_Prod 
2024-04-08 09:48:31,570 [INFO] ----------Extract----------
2024-04-08 09:48:31,571 [INFO] controller.prod.appd-saas.srv.westpac.com.au - Extracting APM Applications
2024-04-08 09:48:31,750 [INFO] controller.prod.appd-saas.srv.westpac.com.au - EUM Applications
2024-04-08 09:48:32,622 [INFO] controller.prod.appd-saas.srv.westpac.com.au - MRUM Applications
2024-04-08 09:48:33,210 [INFO] controller.prod.appd-saas.srv.westpac.com.au - Extracting Servers
2024-04-08 09:48:45,066 [ERROR] Traceback (most recent call last):
  File "uplink\clients\io\asyncio_strategy.py", line 17, in invoke
  File "uplink\hooks.py", line 109, in handle_exception
  File "six.py", line 719, in reraise
  File "uplink\clients\io\asyncio_strategy.py", line 17, in invoke
  File "uplink\clients\aiohttp_.py", line 135, in send
  File "aiohttp\client.py", line 544, in _request
  File "aiohttp\client_reqrep.py", line 890, in start
  File "aiohttp\streams.py", line 604, in read
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core\Engine.py", line 205, in run
  File "core\Engine.py", line 340, in process
  File "extractionSteps\general\ControllerLevelDetails.py", line 38, in extract
  File "api\appd\AppDService.py", line 758, in getServers
  File "util\asyncio_utils.py", line 28, in gatherWithConcurrency
  File "util\asyncio_utils.py", line 26, in semTask
  File "uplink\clients\io\asyncio_strategy.py", line 38, in execute
  File "uplink\clients\io\asyncio_strategy.py", line 20, in invoke
  File "uplink\clients\io\asyncio_strategy.py", line 20, in invoke
  File "uplink\clients\io\asyncio_strategy.py", line 20, in invoke
  File "uplink\clients\io\execution.py", line 108, in on_failure
  File "uplink\clients\io\interfaces.py", line 303, in fail
  File "six.py", line 719, in reraise
  File "uplink\clients\io\asyncio_strategy.py", line 17, in invoke
  File "uplink\hooks.py", line 108, in handle_exception
  File "uplink\hooks.py", line 20, in wrapper
  File "api\appd\AppDController.py", line 9, in raise_api_error
api.appd.AppDController.ApiError: Server disconnected

Notification from AppD SaaS Ops:

*******
For Improved performance and Security, Your AppDynamics hosted server requires general maintenance. During this maintenance, We will add support for TLS 1.3 protocol and cipher suites along with currently supported TLS protocols and cipher suites. The work will last from Tuesday April 2nd 2024, 10:00:00 AM PDT (Tuesday April 2nd 2024, 5:00:00 PM UTC) until Tuesday April 2nd 2024, 1:00:00 PM PDT (Tuesday April 2nd 2024, 8:00:00 PM UTC).

We appreciate your continued relationship with us and trust in our solution.

Should you have any questions related to this notification, please contact AppDynamics at help.appdynamics.com

To see the current status of your service, and view an archive of previous messages, please visit the AppDynamics Status Page 

Sincerely,
AppDynamics Operations Team
********

Kind regards,
Simon

**Comment by alexafshar** [comment]
We don't have any customers that have TLS 1.3 enabled reporting this.  Also internally sales engineer didn't have an issue running cat against controller.   I am setting up a TLS 1.3 enabled controller anyways and will validated.   Note I removed logged info from your posting and tracking internally.
