### ISSUE TITLE
Issue when Controller rest api response has non standard characters

### ISSUE THREAD

**Issue by agbidi** [Appdynamics/config-assessment-tool#31]
I suspect one of my French customers has 'é' characters in the rest api response and  this is causing an issue with the backend:

2021-12-21 14:48:14,539 [ERROR] Traceback (most recent call last):
  File "/backend/core/Engine.py", line 88, in run
    await self.initControllers()
  File "/backend/core/Engine.py", line 155, in initControllers
    dashboards = await asyncio.gather(*getDashboards)
  File "/backend/api/appd/AppDService.py", line 454, in getDashboards
    for dashboard in [await self.getResultFromResponse(response, debugString) for response in response]:
  File "/backend/api/appd/AppDService.py", line 454, in <listcomp>
    for dashboard in [await self.getResultFromResponse(response, debugString) for response in response]:
  File "/backend/api/appd/AppDService.py", line 498, in getResultFromResponse
    body = (await response.content.read()).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 6507: invalid continuation byte

Could you look into it please?

Alex Agbidinoukoun

**Comment by bhjelmar** [comment]
@agbidi Thanks for raising this request, we are looking into it.
